### ISSUE TITLE
ansible-playbook: error: no such option: --authtype

### ISSUE THREAD

**Issue by MrAmbiG** [TerryHowe/ansible-modules-hashivault#101]
This is what I ran
`ansible-playbook --authtype=approle vault_list.yaml`
The output was
```
Usage: ansible-playbook [options] playbook.yml [playbook2 ...]

ansible-playbook: error: no such option: --authtype

```
module name:- hashivault_list.py
playbook content:-
```
---
- hosts: localhost
  tasks:
    - hashivault_list:
        secret: '/<mypath>'
      register: vault
```
