### ISSUE TITLE
enable auth leads to missing client token error

### ISSUE THREAD

**Issue by Sam-Mumm** [TerryHowe/ansible-modules-hashivault#115]
Hello,

I use the following configuration:

- ansible==2.7.7
- ansible-modules-hashivault==3.16.0
- hashicorp vault:  0.11.4

and I don't know if I used wrong or I found a bug but when I try:

```
- name: Enable LDAP Authentifikation
  hashivault_auth_enable:
    name: "ldap"
    url: "https://vault.example.com:8200"
    ca_cert: "/etc/vault/ssl/materna-chain.crt"
    client_cert: "/etc/vault/ssl/vault.example.crt"
    client_key: "/etc/vault/ssl/vault.example.key"
    token: "k6shEQnNK7o6g85ql1y98eQI"
    authtype: ldap
```

I get the error:

`fatal: [alm-k8s-2.materna.de]: FAILED! => {"changed": false, "msg": "Exception: missing client token", "rc": 1}`

the strange thing is if I try another operation e.g. creating a policy it works. Maybe someone here can give me a hint what I am doing wrong or confirm the bug.
best regards
Dan
