### ISSUE TITLE
No line feed at the end of the last line when issuing a certificate from vault

### ISSUE THREAD

**Issue by libussa** [TerryHowe/ansible-modules-hashivault#138]
When using `hashivault_write` to issue a certificate from a pki, the files I get lack an end-of-line character in the last line. This causes issues when using those files (for example when needing to concatenate them)

This is the roles I'm using:

```
- name: Issue certificates from Vault
  become: false
  hashivault_write:
    secret: "/my_pki/issue/server-certificate"
    data:
      common_name: "{{ inventory_hostname }}"
      format: "pem"
      ttl: "8670h"
      alt_names: "{{ alt_names_list |unique|join(',') }}"
      ip_sans: "{{ ip_sans_list |unique|join(',') }}"
  delegate_to: localhost
  register: certificate_issue

- name: Write data to another variable
  set_fact:
    certificate_issue_data={{ certificate_issue.data }}

- name: Write server certificate
  copy: 
    content: "{{ certificate_issue_data.data.certificate }}"
    dest: "/etc/ssl/certs/{{ inventory_hostname_short }}.crt" 
    mode: "u=rw,g=r,o=r" 
    owner: "root"
    group: "root"

- name: Write server key
  copy: 
    content: "{{ certificate_issue_data.data.certificate }}"
    dest: "/etc/ssl/certs/{{ inventory_hostname_short }}.key" 
    mode: "u=rw,g=r,o=r" 
    owner: "root"
    group: "root"
```

**Comment by TerryHowe** [comment]
You may have an easier time with this from docs:
```
    ---
    - hashivault_read_to_file:
        secret: 'ssl_certs'
        key: 'der_format'
        dest: 'ssl_cert.cer'
    - hashivault_write_from_file:
        secret: 'ssl_certs'
        key: 'der_format'
        path: 'ssl_cert.cer'
```

You may also be able to overcome this with base64 encoding and/or ansible/jinja2 templating.  The problem you are having is a bit of a ansible string problem.
