### ISSUE TITLE
hashivault_db_secret_engine_role false failure

### ISSUE THREAD

**Issue by Dudesons** [TerryHowe/ansible-modules-hashivault#142]
Hi @TerryHowe  @drewmullen ,

I try to use the `hashivault_db_secret_engine_role` action but ansible return me an error whereas vault was correctly setup
So the action work but I don't understand why ansible failed :(

```
failed: [localhost] (item={u'default_ttl': 600, u'state': u'present', u'db_name': u'scyllav3', u'name': u'scylla_backup_v3', u'max_ttl': 600, u'creation_statements': u"CREATE USER '{{username}}' WITH PASSWORD '{{password}}' NOSUPERUSER; GRANT dba TO {{username}};"}) => {
    "changed": false, 
    "item": {
        "creation_statements": "CREATE USER '{{username}}' WITH PASSWORD '{{password}}' NOSUPERUSER; GRANT dba TO {{username}};", 
        "db_name": "scyllav3", 
        "default_ttl": 600, 
        "max_ttl": 600, 
        "name": "scylla_backup_v3", 
        "state": "present"
    }, 
    "module_stderr": "", 
    "module_stdout": "[u'identity/', u'database/', u'consul/', u'sys/', u'secret/', u'cubbyhole/']\n\n{\"invocation\": {\"module_args\": {\"rollback_statements\": [], \"renew_statements\": [], \"client_key\": \"\", \"mount_point\": \"database\", \"verify\": true, \"namespace\": null, \"role_id\": \"\", \"state\": \"present\", \"client_cert\": \"\", \"username\": \"\", \"authtype\": \"token\", \"creation_statements\": [\"CREATE USER '{{username}}' WITH PASSWORD '{{password}}' NOSUPERUSER; GRANT dba TO {{username}};\"], \"ca_cert\": \"\", \"token_ttl\": 600, \"token_max_ttl\": 600, \"secret_id\": \"\", \"db_name\": \"scyllav3\", \"password\": \"\", \"revocation_statements\": [], \"name\": \"scylla_backup_v3\", \"url\": \"https://vault.dev.veepeez.io:8200\", \"role_file\": null, \"token\": \"VALUE_SPECIFIED_IN_NO_LOG_PARAMETER\", \"ca_path\": \"\"}}, \"changed\": false, \"rc\": 0}\n", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 0
}
```

Someone have an idea ?

**Comment by drewmullen** [comment]
can you please provide a example of your play

**Comment by Dudesons** [comment]
`the syntax for the sql statements is quite strange` => because it's not sql but cql (cassandra query language)

data:
```yaml
vpz_vault_db_secret_engine_roles:
  - name: scylla_backup
    db_name: scylla
    creation_statements: !unsafe "CREATE USER '{{username}}' WITH PASSWORD '{{password}}' NOSUPERUSER; GRANT dba TO {{username}};"
    default_ttl: 600
    max_ttl: 600
    state: present
  - name: scylla_backup_v3
    db_name: scyllav3
    creation_statements: !unsafe "CREATE USER '{{username}}' WITH PASSWORD '{{password}}' NOSUPERUSER; GRANT dba TO {{username}};"
    default_ttl: 600
    max_ttl: 600
    state: present
```

play:
```yaml
- name: Set up database roles
  hashivault_db_secret_engine_role:
    token: "{{ vpz_vault_management_token }}"
    url: "{{ vpz_vault_management_global_endpoint }}"
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    token_ttl: "{{ item.default_ttl | default(0) }}"
    token_max_ttl: "{{ item.max_ttl | default(0) }}"
    db_name: "{{ item.db_name }}"
    creation_statements: "{{ item.creation_statements }}"
    revocation_statements: "{{ item.revocation_statements | default([]) }}"
    rollback_statements: "{{ item.rollback_statements | default([]) }}"
    renew_statements: "{{ item.renew_statements | default([]) }}"
  with_items: "{{ vpz_vault_db_secret_engine_roles }}"
```
