### ISSUE TITLE
hashivault_write with update and version 2 messes up the structure

### ISSUE THREAD

**Issue by rnsc** [TerryHowe/ansible-modules-hashivault#163]
Hello,

I've been testing this awesome library and it looks like I'm hitting an issue when using a KV in version 2 and the update flag.
Playbook tasks:

```yaml
    - name: "hashivault_write | write password"
      delegate_to: localhost
      hashivault_write:
        mount_point: my_secret_kv
        secret: "{{ kv_path + '/vars_test' }}"
        version: 2
        data:
          user1: "password1"

    - debug:
        msg: "{{ lookup('hashi_vault', 'secret=my_secret_kv/data/'+kv_path+'/vars_test') }}"

    - name: "hashivault_write | write another password"
      delegate_to: localhost
      hashivault_write:
        mount_point: my_secret_kv
        secret: "{{ kv_path + '/vars_test' }}"
        version: 2
        update: true
        data:
          user2: "password2"

    - debug:
        msg: "{{ lookup('hashi_vault', 'secret=my_secret_kv/data/'+kv_path+'/vars_test') }}"
```

Result:
```
TASK [hashivault_write | write password] **************************************************************************************************************************************************************************************************************
Friday 27 September 2019  16:27:09 +0200 (0:00:00.662)       0:00:05.967 ******
Friday 27 September 2019  16:27:09 +0200 (0:00:00.662)       0:00:05.967 ******
changed: [localhost -> localhost]

TASK [debug] ******************************************************************************************************************************************************************************************************************************************
Friday 27 September 2019  16:27:09 +0200 (0:00:00.529)       0:00:06.497 ******
Friday 27 September 2019  16:27:09 +0200 (0:00:00.529)       0:00:06.496 ******
ok: [localhost] =>
  msg:
    data:
      user1: password1
    metadata:
      created_time: '2019-09-27T14:27:09.548159353Z'
      deletion_time: ''
      destroyed: false
      version: 1

TASK [hashivault_write | write another password] ******************************************************************************************************************************************************************************************************
Friday 27 September 2019  16:27:10 +0200 (0:00:00.649)       0:00:07.147 ******
Friday 27 September 2019  16:27:10 +0200 (0:00:00.649)       0:00:07.146 ******
changed: [localhost -> localhost]

TASK [debug] ******************************************************************************************************************************************************************************************************************************************
Friday 27 September 2019  16:27:10 +0200 (0:00:00.622)       0:00:07.769 ******
Friday 27 September 2019  16:27:10 +0200 (0:00:00.622)       0:00:07.768 ******
ok: [localhost] =>
  msg:
    data:
      data:
        user1: password1
      metadata:
        created_time: '2019-09-27T14:27:09.548159353Z'
        deletion_time: ''
        destroyed: false
        version: 1
      user2: password2
    metadata:
      created_time: '2019-09-27T14:27:10.818319333Z'
      deletion_time: ''
      destroyed: false
      version: 2
```

If I then want to view my secrets in the web UI, I only see a JSON because the structure of the object is messed up.

I'm able to bypass this issue using this trick:

```yaml
data: "{{ (lookup('hashi_vault', 'my_secret_kv/data/'+kv_path+'/vars')).data | combine(new_secrets) }}"
```
new_secrets is just a dictionary like this:
```yaml
new_secrets:
  user2: "password2"
```
But I'd rather use the "update: true" option for readability and ease of use.

I hope I gave enough information to debug this!
