### ISSUE TITLE
hashivault_audit_enable indepotence issue

### ISSUE THREAD

**Issue by DrMagPie** [TerryHowe/ansible-modules-hashivault#186]
Hi,

I'm facing odd issue with hashivault_audit_enable module,
If I'm using following configuration item then everything works fine.
```yml
- name: Enable Audit Log
  run_once: true
  register: result
  delegate_to: localhost
  hashivault_audit_enable:
    url: "{{ vault_addr }}"
    ca_cert: "{{ root_ca_crt }}"
    verify: "{{ verify }}"
    authtype: approle
    role_id: "{{ role_id }}"
    secret_id: "{{ secret_id }}"
    name: "syslog"
    options:
      tag: vault
      facility: AUTH
```
OUTPUT:
```
PLAY [localhost] ***************************************************************************************************************************************************************************
TASK [Gathering Facts] *********************************************************************************************************************************************************************
ok: [localhost]

TASK [config : Enable Audit Log] ***********************************************************************************************************************************************************
changed: [localhost -> localhost]

TASK [config : Enable Audit Log] ***********************************************************************************************************************************************************
ok: [localhost -> localhost]

TASK [config : Enable Audit Log] ***********************************************************************************************************************************************************
ok: [localhost -> localhost]

TASK [config : Enable Audit Log] ***********************************************************************************************************************************************************
ok: [localhost -> localhost]

TASK [config : Enable Audit Log] ***********************************************************************************************************************************************************
ok: [localhost -> localhost]
```

But if we add `hmac_accessor: false` option then everything breaks

```yml
- name: Enable Audit Log
  run_once: true
  register: result
  delegate_to: localhost
  hashivault_audit_enable:
    url: "{{ vault_addr }}"
    ca_cert: "{{ root_ca_crt }}"
    verify: "{{ verify }}"
    authtype: approle
    role_id: "{{ role_id }}"
    secret_id: "{{ secret_id }}"
    name: "syslog"
    options:
      tag: vault
      facility: AUTH
      hmac_accessor: false
```
OUTPUT:
```
PLAY [localhost] ***************************************************************************************************************************************************************************
TASK [Gathering Facts] *********************************************************************************************************************************************************************
ok: [localhost]

TASK [config : Enable Audit Log] **********************************************************************************************************************************************************
*changed: [localhost -> localhost]

TASK [config : Enable Audit Log] ***********************************************************************************************************************************************************
fatal: [localhost -> localhost]: FAILED! => {
    "changed": false,
    "rc": 1
}

MSG:

Exception: path already in use
```

I had quick look at modules source code, and I don't see what could cause this issue.
So probably issue comes from HVAC package.
but might be I have missed something so could you please investigate this.
