### ISSUE TITLE
SSL issue

### ISSUE THREAD

**Issue by mark1973ryan** [TerryHowe/ansible-modules-hashivault#203]
Hi,

I've seen a closed issue on this already but I can't determine the solution. We cannot pass creds in the clear so switching ssl verify off is not an option.
This is a self-signed cert as we're in a sandpit. I used update-ca-trust to add the pem file to the bundle.

VAULT_CACERT=/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
VAULT_TOKEN=<redacted>
VAULT_ADDR=https://vault.nbs-stp.co.uk:8200
VAULT_CLIENT_CERT=/etc/pki/ca-trust/source/anchors/vault-selfsigned-crt.pem
VAULT_CLIENT_KEY=/etc/pki/ca-trust/source/anchors/vault-selfsigned-key.pem

```yaml
- name: Vault lookup test
  connection: local
  gather_facts: false
  hosts: 127.0.0.1
  tasks:
    - name: vault lookup
      debug:
        msg: "{{ lookup('hashi_vault', 'secret=serviceaccounts/data/testsite') }}"
```

I get the following:

TASK [using certificate auth] *******************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'hashi_vault'. Error was a <class 'requests.exceptions.SSLError'>, original message: HTTPSConnectionPool(host='vault.nbs-stp.co.uk', port=8200): Max retries exceeded with url: /v1/auth/token/lookup-self (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618)'),))"}

If I use a URI module task with the client paths set ti works no problem but having to stick a task in every time isn't as clean. I set the environment variables using custom credentials in a the AWX tower.

```yaml
- name: Vault credential fetch
  connection: local
  gather_facts: false
  hosts: localhost
  tasks:
  
    - name: Get vault credentials
      uri:
        url: "{{ lookup('env','VAULT_ADDR') }}{{ lookup('env','VAULT_PATH') }}"
        method: GET
        validate_certs: true
        client_cert: /etc/pki/ca-trust/source/anchors/vault-selfsigned-crt.pem
        client_key: /etc/pki/ca-trust/source/anchors/vault-selfsigned-key.pem
        headers:
          X-Vault-Token: "{{ lookup('env','VAULT_TOKEN') }}"
      register: vault_response
```

If anyone can spot the obvious that would be great.

Thanks in advance Mark
