### ISSUE TITLE
hashivault_auth_method

### ISSUE THREAD

**Issue by metanovii** [TerryHowe/ansible-modules-hashivault#209]
Hi, i try use hashivault_auth_method module in ansible task like that:

-   hashivault_auth_method:
        config:
          kubernetes_host: "{{ k8s_api_endpoint }}"
          kubernetes_ca_cert: "{{ lookup('file','{{playbook_dir}}/../artifacts/ca.crt') }}"
          token_reviewer_jwt: "{{ k8s_token_vault.stdout }}"
      method_type: kubernetes
      mount_point: "some_k8s_path"
      state: "enabled"

After task i have rc 0 , but in some_k8s_path all field empty.

**Comment by TerryHowe** [comment]
It may be because you are talking to a different version or configuration of vault? More detail would help like in situation A I send this and get that. In situation B I send this and get that.

**Comment by metanovii** [comment]
Task:
```
- hashivault_auth_method:
    config:
      kubernetes_host: "https://1azaza:8443"
      kubernetes_ca_cert: "test"
      token_reviewer_jwt: "eyJhbGciOiJSUzI1NiIsImtpZCI6ImJTSjE5dTdFZVBxeDRmc3pRZVNscWFWNm1Wck04TDEzVDVpOEE2WDFkdkEifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InZhdWx0LWF1dGgtdG9rZW4td3RibTIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoidmF1bHQtYXV0aCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjgwZDQzMGExLTBhMDUtNGUwNi1hODAyLTAzZjhjNjcwZDU1ZSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OnZhdWx0LWF1dGgifQ.t3doAJRDSdFGNDsGczT4sziw2uxObsI7UNb0CPuDq91a-SsXdNAUT3bG-KfRYO-AgPwJ8UEYF1uyJYKtI3E_SCXNXyLvq_ccpj7YySnf7Qk7ohEGmPaTyviPbw327V8o-EPlduJaNj8oXxLcAPspqlyz1f42WuzfOtX6O1RY27qzDqm1TXgmip-go2M3Q5niOSN0IgzaMvUO08sQRwRqZL7_T8-uM40p88F9Em2JmKo_laWBwQ0HcTTXBd_HjxELromNsGdxFSSThP2ZfyEyNhk5NfXp5jMcyabeWr5FbnRE7dSoa85nny0JV5zQLjY1lxe7Kq56tU7egs7HRWfjqQ"
    method_type: kubernetes
    mount_point: "k8s-qa-test-local"
    state: "enabled"
```
Debug task:

```
null_resource.k8s_init (local-exec): changed: [localhost] => {
null_resource.k8s_init (local-exec):     "changed": true,
null_resource.k8s_init (local-exec):     "created": false,
null_resource.k8s_init (local-exec):     "invocation": {
null_resource.k8s_init (local-exec):         "module_args": {
null_resource.k8s_init (local-exec):             "authtype": "userpass",
null_resource.k8s_init (local-exec):             "ca_cert": "",
null_resource.k8s_init (local-exec):             "ca_path": "",
null_resource.k8s_init (local-exec):             "client_cert": "",
null_resource.k8s_init (local-exec):             "client_key": "",
null_resource.k8s_init (local-exec):             "config": {
null_resource.k8s_init (local-exec):                 "default_lease_ttl": 2764800,
null_resource.k8s_init (local-exec):                 "force_no_cache": false,
null_resource.k8s_init (local-exec):                 "kubernetes_ca_cert": "test",
null_resource.k8s_init (local-exec):                 "kubernetes_host": "https://1azaza:8443",
null_resource.k8s_init (local-exec):                 "max_lease_ttl": 2764800,
null_resource.k8s_init (local-exec):                 "token_reviewer_jwt": "eyJhbGciOiJSUzI1NiIsImtpZCI6ImJTSjE5dTdFZVBxeDRmc3pRZVNscWFWNm1Wck04TDEzVDVpOEE2WDFkdkEifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InZhdWx0LWF1dGgtdG9rZW4td3RibTIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoidmF1bHQtYXV0aCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjgwZDQzMGExLTBhMDUtNGUwNi1hODAyLTAzZjhjNjcwZDU1ZSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OnZhdWx0LWF1dGgifQ.t3doAJRDSdFGNDsGczT4sziw2uxObsI7UNb0CPuDq91a-SsXdNAUT3bG-KfRYO-AgPwJ8UEYF1uyJYKtI3E_SCXNXyLvq_ccpj7YySnf7Qk7ohEGmPaTyviPbw327V8o-EPlduJaNj8oXxLcAPspqlyz1f42WuzfOtX6O1RY27qzDqm1TXgmip-go2M3Q5niOSN0IgzaMvUO08sQRwRqZL7_T8-uM40p88F9Em2JmKo_laWBwQ0HcTTXBd_HjxELromNsGdxFSSThP2ZfyEyNhk5NfXp5jMcyabeWr5FbnRE7dSoa85nny0JV5zQLjY1lxe7Kq56tU7egs7HRWfjqQ",
null_resource.k8s_init (local-exec):                 "token_type": "default-service"
null_resource.k8s_init (local-exec):             },
null_resource.k8s_init (local-exec):             "description": null,
null_resource.k8s_init (local-exec):             "method_type": "kubernetes",
null_resource.k8s_init (local-exec):             "mount_point": "k8s-qa-test-local",
null_resource.k8s_init (local-exec):             "namespace": null,
null_resource.k8s_init (local-exec):             "password": "very_secure_password",
null_resource.k8s_init (local-exec):             "role_id": "",
null_resource.k8s_init (local-exec):             "secret_id": "",
null_resource.k8s_init (local-exec):             "state": "enabled",
null_resource.k8s_init (local-exec):             "token": "",
null_resource.k8s_init (local-exec):             "url": "https://very_secury_host",
null_resource.k8s_init (local-exec):             "username": "terraform",
null_resource.k8s_init (local-exec):             "verify": true
null_resource.k8s_init (local-exec):         }
null_resource.k8s_init (local-exec):     },
null_resource.k8s_init (local-exec):     "rc": 0
null_resource.k8s_init (local-exec): }
