### ISSUE TITLE
Module ignores the no_log parameter when using env variables

### ISSUE THREAD

**Issue by stokkie90** [TerryHowe/ansible-modules-hashivault#243]
When running ansible/awx using this module we can see the role_id/secret_id or the token in plain text. This is only when using the environment. The defaults in the `hashivault_argspec` definition in `module_utils/hashivault.py`:

```
        token=dict(required=False, default=hashivault_default_token(), type='str', no_log=True),
        password=dict(required=False, default=os.environ.get('VAULT_PASSWORD', ''), type='str', no_log=True),
        role_id=dict(required=False, default=os.environ.get('VAULT_ROLE_ID', ''), type='str', no_log=True),
        secret_id=dict(required=False, default=os.environ.get('VAULT_SECRET_ID', ''), type='str', no_log=True),
        aws_header=dict(required=False, default=os.environ.get('VAULT_AWS_HEADER', ''), type='str', no_log=True),
```

I'm not sure if this is default for ansible modules but seems quite strange. 

When specifying `token: "{{ lookup('env', 'VAULT_TOKEN') }}"` for example then it will output  `VALUE_SPECIFIED_IN_NO_LOG_PARAMETER`

**Comment by TerryHowe** [comment]
Sample code maybe?  Which module are you using? The example you gave in the last sentence sounds like it is working, that should not be logged although I'm not sure why you are using the lookup plugin there when it should do that without specifying the value.

**Comment by stokkie90** [comment]
Sample code that outputs the token/role_id/secret_id in plain text:

```
    - name: "[prod] Write test to vault"
      hashivault_write:
        secret: "{{ database_dynamic_basepath }}{{ role.path | splitext | first }}"
        data:
          db_name: "{{ db_name }}"
          creation_statements: "{{ creation_statements }}"
      when: creation_statements != read_from_vault.value.creation_statements[0] or db_name != read_from_vault.value.db_name
      register: write_to_vault
```

Will result in:
```
changed: [localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "alternate_data": {},
            "authtype": "token",
            "aws_header": "",
            "ca_cert": "",
            "ca_path": "",
            "client_cert": "",
            "client_key": "",
            "data": {
                "creation_statements": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "db_name": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
            },
            "login_mount_point": null,
            "mount_point": "secret",
            "namespace": null,
            "password": "",
            "role_id": "",
            "secret": "/database-dynamic/roles/product-api-rw",
            "secret_id": "",
            "token": "s.aJeTe3passwordMxNHQzZen9",
            "update": false,
            "url": "http://localhost:8200",
            "username": "",
            "verify": false,
            "version": 1
        }
    },
    "msg": "Secret database-dynamic/roles/product-api-rw written",
    "rc": 0
}
```

When for example add the following line to the task: `token: "{{ lookup('env', 'VAULT_TOKEN') }}"` (Lookup plugin is just being used as example) the thing is when you specify the tasks instead of relying on the `os.defaults.get()` it works. 

the invocation output will not put the token in plain text. `"token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",`

Looking a little bit at the code i can not find the issue.

**Comment by TerryHowe** [comment]
This is an ansible issue, there is nothing we can do about it. My recommendation would be don't use such a high verbosity level or set no_log in your ansible:
```
    - hashivault_write:
        secret: greenday
        data:
          tre: cool
      no_log: True
```

One of many related issues https://github.com/ansible/ansible/issues/17911
