### ISSUE TITLE
Modules report changed due to type mismatch

### ISSUE THREAD

**Issue by jamielennox** [TerryHowe/ansible-modules-hashivault#247]
Me again, I promise i'm doing this to help not be a pain :) 

So this is kind of an inbuilt problem with ansible, but I _think_ it might be something that can be worked around. There are a lot of places where vault expects and returns an integer value. The ones that are getting me at the moment are all the TTLs in certificates. However due to the way jinja works ansible generally only templates out strings.

Taking a new-ish example: 

```
- hosts: localhost
  tasks:
    - hashivault_pki_role:
        name: tester
        config:
          allow_subdomains: true
          ttl: 3600
```

this should work because the ttl is an integer and the values returned by the vault APIs are integers, if i put that into a loop though: 

```
- hosts: localhost
  tasks:
    - hashivault_pki_role:
        name: "{{ item.name }}"
        config:
          allow_subdomains: "{{ item.allow_subdomains | default(omit) }}"
          ttl: "{{ item.ttl | default('3600') }}"
      loop: "{{ roles }}"
```

This will always return changed and update because the ttl value is a string, being compared to an integer even though the value is the same. 

There is actually a relatively new feature on the ansible side that can let a jinja value be templated and return a non-string type: https://docs.ansible.com/ansible/latest/reference_appendices/config.html#default-jinja2-native but it's not really ideal to set that at the cfg level. 

I think the easiest way to fix this would be to cast everything to strings in the compare function? Or at least check if the return value is a native type (int, float, ?) and then cast both sides to string before doing the check? 

Note: i'm typing this directly into the bug, so my examples probably don't work perfectly, but hopefully show the problem.
