### ISSUE TITLE
lookup plugin can't be configured with local url, tokens etc

### ISSUE THREAD

**Issue by jamielennox** [TerryHowe/ansible-modules-hashivault#250]
All the hashivault_ modules use the common hashivault argspec that adds common features such as url, certs, and auth information via the common: https://github.com/TerryHowe/ansible-modules-hashivault/blob/cfa9d187d9cfbfbf260edc8744a6ead8cba1ea49/ansible/module_utils/hashivault.py#L10

The lookup plugin doesn't (can't?) use this function and so does it's own way: https://github.com/TerryHowe/ansible-modules-hashivault/blob/cfa9d187d9cfbfbf260edc8744a6ead8cba1ea49/ansible/plugins/lookup/hashivault.py#L41 

This reads the auth information from environment variables but doesn't allow you to pass this via variables. 

This is relevant to me because I've got independent vaults I'm trying to loop over in different regions so need to auth individually to each. This can be done via the modules but I can't use the lookup plugin.

**Comment by TerryHowe** [comment]
I guess `kwargs` there could be expanded, but as a work around, you can't use ansible environment?

```
---
- hosts: localhost
  gather_facts: no
  environment:
      VAULT_TOKEN: s.7qqqvUdUdr2d5o8NytCVjMw2
  tasks:
    - set_fact:
        a_set_fie: "{{lookup('hashivault', 'basic', 'fie')}}"
    - assert: { that: "'{{a_set_fie}}' == 'fum'" }
```
