### ISSUE TITLE
hashivault_write: data: name of key can not be defined from variable

### ISSUE THREAD

**Issue by Wolfsrudel** [TerryHowe/ansible-modules-hashivault#314]
In the following code snippet the variable "{{ item.1.key }}" isn't interpolated for section "data":
```
- name: "Ensure secrets are present."
  hashivault_write:
    mount_point: "{{ item.1.mount_point }}"
    secret: "{{ item.1.path }}/{{ item.1.name }}"
    data:
      "{{ item.1.key }}": "tobeset"
  with_subelements:
    - "{{ vault.secrets }}"
    - key_value
```

Result in debug:
```
"data": {
    "{{ item.1.key }}": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
},
```

The variable is defined with the value "token", but could be everthing.
Is this a standard behavior and shouldn't it work that way?

Ansible version is 2.10.0
Python version is 3.6.2
Module is installed using pip and is version 4.5.6
