### ISSUE TITLE
Since version 4.5.5 included, policies list is not applied to AppRole 

### ISSUE THREAD

**Issue by ericcitaire** [TerryHowe/ansible-modules-hashivault#323]
After updating `ansible-modules-hashivault`, I struggled with a missing policy on an AppRole :
```yaml
    - hashivault_approle_role:
        name: foo-app
        policies:
        - foo-policy
```
After playing this, `foo-policy` is not assigned to `foo-app` AppRole.

After some digging, I found out that `hashivault_approle_role` works fine in version 4.5.4 and stops working properly in version 4.5.5.

It seems that #280 might be involved. Didn't have the time to investigate further more.
