### ISSUE TITLE
config item 'not_before_duration' has wrong data format

### ISSUE THREAD

**Issue by jxsl13** [TerryHowe/ansible-modules-hashivault#339]
According to the documentation 30s is the default value which I did set.
https://terryhowe.github.io/ansible-modules-hashivault/modules/hashivault_pki_role_module.html#hashivault-pki-role-module

The role creation payload:
https://github.com/jxsl13/vault-test/blob/7672a6bd928235458dfbc42cf1e88df60d706ca4/stages/config/pki.yaml#L27

the file from above is used as payload in this step:
https://github.com/jxsl13/vault-test/blob/master/stages/09-configure-pki.yaml#L66

error message:
```
ansible-vault-configuration | TASK [create {{ item }} role] **************************************************
ansible-vault-configuration | failed: [127.0.0.1] (item=pki-issuer) => {"ansible_loop_var": "item", "changed": false, "item": "pki-issuer", "msg": "config item 'not_before_duration' has wrong data format", "rc": 0}
```

file where this error originates from:
https://github.com/TerryHowe/ansible-modules-hashivault/blob/25d53be8c9c1cb98e168eb3eb1a9e3bc10b45173/ansible/modules/hashivault/hashivault_pki_role.py

**Comment by jxsl13** [comment]
Seemingly **hashivault_pki_role** also does not check whether a given role with the corresponding configuration already exists leading to an always changed state.

This might be caused by this issue or might be a completely different issue.

I'm always getting the status changed returned for this here:

```yaml
  - name: "create {{ item }} role"
    hashivault_pki_role:
      state: present
      name: "{{ item }}"
      #https://terryhowe.github.io/ansible-modules-hashivault/modules/hashivault_pki_role_module.html#examples
      config: "{{ lookup('template', 'config/pki.yaml') | from_yaml }}"
    environment: "{{ remote_env }}"
    with_items: "{{ policies.names }}"
    when: configurePKIEnabled and 'pki' in item.lower()
```

https://github.com/jxsl13/vault-test/blob/master/stages/11-configure-pki.yaml#L61-L69
