### ISSUE TITLE
hashivault_write not checking whether data already exists

### ISSUE THREAD

**Issue by jxsl13** [TerryHowe/ansible-modules-hashivault#341]
Is it possible to add this?
Seemingly when I do write data like this, I always get a changed state, even tho the data already exists:

https://github.com/jxsl13/vault-test/blob/25357aebf6b93b06fe13504d119568e705df366e/stages/12-configure-ssh.yaml#L71-L88

```yaml
  - name: "create {{ item }} role"
    hashivault_write:
      mount_point: ssh
      secret: "roles/{{ item }}"
      data:
        allow_user_certificates: true
        allowed_users: "*"
        allowed_extensions: "permit-pty,permit-port-forwarding"
        default_extensions:
          - permit-pty: ""
          - permit-port-forwarding: ""
        key_type: "ca"
        #default_user: "ubuntu"
        ttl: "30m0s"
    environment: "{{ remote_env }}"
    register: ssh_role_result
    when: configureSSHEnabled and 'ssh' in item.lower()
    with_items: "{{ policies.names }}"
```

**Comment by TerryHowe** [comment]
The `update: True` should be idempotent, but there were issues reading all the time in some situations.

**Comment by jxsl13** [comment]
will try, thanks. I can imagine that there might be a problem with reading arbitrary data.

**Comment by jxsl13** [comment]
in this case it seems to always "change" the state.

**Comment by TerryHowe** [comment]
Huh, we have automated tests for that, but maybe they aren't thorough enough?

**Comment by jxsl13** [comment]
This example might help?

```yaml
- name: stage 12 - configure SSH
  hosts: all

  gather_facts: true
  tasks:

# have the vault unsealed and cluster_keys.json in the current fodler
  - name: load cluster_keys.json var from file for ssh
    include_vars:
      file: "cluster_keys.json"
      name: cluster_keys

# generate private and public key in current folder with: ssh-keygen -t rsa -b 4096 -q -N "" -f ssh
  - name: get environment & variables
    set_fact:
      privateKeyLocation: "ssh"
      publicKeyLocation: "ssh.pub"
      remote_env:
        KUBECONFIG: "{{ '~/.kube/config'.replace('~', ansible_env.HOME) }}"
        VAULT_ADDR: "http://127.0.0.1:8200"                                            ##### replace this
        VAULT_TOKEN: "{{ cluster_keys.root_token }}"

  - name: read public & private keys
    set_fact:
      privateKey: "{{ lookup('file', privateKeyLocation) }}"
      publicKey: "{{ lookup('file', publicKeyLocation) }}"

  - name: enable SSH secrets engine
    hashivault_secret_engine:
      name: ssh
      backend: ssh
    environment: "{{ remote_env }}"
    register: ssh_engine

  # in case there is no key already in the vault, the above command returns a http 400 status code
  - name: import private & public key
    hashivault_write:
      mount_point: ssh
      secret: config/ca
      data:
        private_key: "{{ privateKey }}"
        public_key: "{{ publicKey }}"
    environment: "{{ remote_env }}"
    register: import_keys

  - name: "create reader role"
    hashivault_write:
      mount_point: ssh
      secret: "roles/reader"
      update: True
      data:
        allow_user_certificates: true
        allowed_users: "*"
        allowed_extensions: "permit-pty,permit-port-forwarding"
        default_extensions:
          - permit-pty: ""
          - permit-port-forwarding: ""
        key_type: "ca"
        #default_user: "ubuntu"
        ttl: "30m0s"
    environment: "{{ remote_env }}"
    register: ssh_role_result
```

**Comment by jxsl13** [comment]
I did check it multiple times, the "create reader role" step does always return a "changed" status.

**Comment by ayav09** [comment]
The task is always returning a changed status because the data doesn't match what is returned from vault. The default "default_extensions" parameter is supposed to be a dictionary (https://www.vaultproject.io/api-docs/secret/ssh#default_extensions), and although it appears vault accepts it as a list, it will return it as a dictionary when reading it. Since it never matches, the module is always going to rewrite the data.

I tested the task with default_extensions as a dictionary and it behaved as expected with a changed status of false.

```
  - name: "create reader role"
    hashivault_write:
      mount_point: ssh
      secret: "roles/reader"
      update: True
      data:
        allow_user_certificates: true
        allowed_users: "*"
        allowed_extensions: "permit-pty,permit-port-forwarding"
        default_extensions:
          permit-pty: ""
          permit-port-forwarding: ""
        key_type: "ca"
        #default_user: "ubuntu"
        ttl: "30m0s"
    environment: "{{ remote_env }}"
    register: ssh_role_result
```
