### ISSUE TITLE
hashivault_init does not return the generated keys in result

### ISSUE THREAD

**Issue by thalesac** [TerryHowe/ansible-modules-hashivault#35]
```
- hashivault_init:
  register: 'vault_init'
  environment:
    VAULT_ADDR: "{{ VAULT_ADDR }}"
  when: vault_init
  run_once: yes

- debug: msg="{{vault_init}}"
```
The debug returns:
```
TASK [platform-vault-init : debug] ******************************************************************
ok: [10.0.20.143] => {
    "msg": true
}
```
It's missing the keys.

This seems to be the culprit: https://github.com/TerryHowe/ansible-modules-hashivault/blob/master/ansible/modules/hashivault/hashivault_init.py#L101

Any ideas?

**Comment by TerryHowe** [comment]
Here is the working functional test if that helps: https://github.com/TerryHowe/ansible-modules-hashivault/blob/master/functional/test_init.yml

The only odd thing I notice is you register vault_init, but have some environment variable of the same name and I *assume* that is what gets printed.

**Comment by thalesac** [comment]
Many thanks Terry, totally my mistake.
I hurried up to open the issue. 
My apologies, you can close this ticket.
Also, Many thanks for your work on this module.

**Comment by dizzler** [comment]
I think your dual use of the vault_init variable is causing a misleading
result from your debug task.

Suggest using some other variable (key) for 'register:' in your
hashivault_init task, then use that new variable as the input to debug
task.


On Oct 25, 2017 12:56 PM, "Thales Ceolin" <notifications@github.com> wrote:

- hashivault_init:
  register: 'vault_init'
  environment:
    VAULT_ADDR: "{{ VAULT_ADDR }}"
  when: vault_init
  run_once: yes

- debug: msg="{{vault_init}}"

The debug returns:

TASK [platform-vault-init : debug]
******************************************************************
ok: [10.0.20.143] => {
    "msg": true
}

It's missing the keys.

This seems to be not working: https://github.com/TerryHowe/
ansible-modules-hashivault/blob/master/ansible/modules/
hashivault/hashivault_init.py#L101

Any ideas?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/TerryHowe/ansible-modules-hashivault/issues/35>, or mute
the thread

**Comment by thalesac** [comment]
Many thanks @dizzler . That was the issue.

Another thing I just came across: I'm trying to re-use the newly generated keys to unseal the vault just after the init:

```
- hashivault_unseal:
    keys: '{{ vault_init_keys.keys_base64 }}'
  environment:
    VAULT_ADDR: "{{ VAULT_ADDR }}"
  when: vault_init_keys
```
This doesn't work. 
As far as I could see, the VAULT_KEYS expect a space separated keys and the vault_init_keys is an array.

If you have any ideas on that would be great.

**Comment by thalesac** [comment]
Replying my own question, I came up with this:

```
- hashivault_unseal:
    keys: '{{ vault_init_keys.keys_base64.0 }} {{ vault_init_keys.keys_base64.1 }} {{ vault_init_keys.keys_base64.2 }}'
  environment:
    VAULT_ADDR: "{{ VAULT_ADDR }}"
  when: vault_init_keys
```

In the future might me nice to generate this automatically. 

Thanks all of you.

**Comment by TerryHowe** [comment]
This is how the function tests do it although your solution is fewer lines

https://github.com/TerryHowe/ansible-modules-hashivault/blob/master/functional/test_init.yml#L17-L21

**Comment by TerryHowe** [comment]
I guess one other thing, you should be able to specify VAULT_ADDR as an argument rather than the environment if you like

```
- hashivault_unseal:
    keys: '{{ vault_init_keys.keys_base64.0 }} {{ vault_init_keys.keys_base64.1 }} {{ vault_init_keys.keys_base64.2 }}'
    url: "{{ VAULT_ADDR }}"
  when: vault_init_keys
```

I didn't test that, but it should work
