### ISSUE TITLE
/data added to the URL path when creating a secret?

### ISSUE THREAD

**Issue by Sispheor** [TerryHowe/ansible-modules-hashivault#378]
Hello, I try to create a secret. 
```yaml
        - name: Add secret
          hashivault_secret:
            token: "{{ vault_token }}"
            verify: no
            mount_point: "secret"
            secret: "CMS-RnD-Lab-Infrastructure/system/testing.gre.hpecorp.net/hello"
            data:
              foo: foe
```

Here is my output
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error Forbidden(1 error occurred:\n\t* permission denied\n\n, on get https://vault.domain.net/v1/secret/data/CMS-RnD-Lab-Infrastructure/system/testing.gre.hpecorp.net/hello) reading secret/CMS-RnD-Lab-Infrastructure/system/testing.gre.hpecorp.net/hello", "rc": 1}
```

`/data` is added to the secret path and that's why I get a permission denied I guess.

If I get the correct URL from the CLI we can see that there is no `/data`
```
vault kv put -output-curl-string secret/CMS-RnD-Lab-Infrastructure/system/testing.gre.hpecorp.net/foo bar=admin 
curl -X PUT -H "X-Vault-Request: true" -H "X-Vault-Token: $(vault print token)" -d '{"bar":"admin"}' https://vault.docker.hpecorp.net/v1/secret/CMS-RnD-Lab-Infrastructure/system/testing.gre.hpecorp.net/foo
```

I missing something? Thanks for any help.
