### ISSUE TITLE
Idempotency issue for hashivault_auth_method

### ISSUE THREAD

**Issue by siwyroot** [TerryHowe/ansible-modules-hashivault#382]
Hello, hashivault_auth_method gets always applied then  ```config```: is defined, module works as expected if ```config:``` is not defined, combination of config option does not matter.

NOT affected:
```
  hashivault_auth_method:
    url: "{{ ocp_install_vault_url }}"
    token: "{{ vault_login_raw.data.auth.client_token }}"
    mount_point: "ocp-install-{{ ocp_install['ocp_cluster_vars']['cluster_id'] }}"
    method_type: kubernetes
    description: "Authentication for flux automation for cluster {{ ocp_install['ocp_cluster_vars']['cluster_id'] }}"
```

Affected code:

```
  hashivault_auth_method:
    url: "{{ ocp_install_vault_url }}"
    token: "{{ vault_login_raw.data.auth.client_token }}"
    mount_point: "ocp-install-{{ ocp_install['ocp_cluster_vars']['cluster_id'] }}"
    method_type: kubernetes
    config:
      default_lease_ttl: 0
      max_lease_ttl: 0
      force_no_cache: False
      token_type: "default-service"
    description: "Authentication for flux automation for cluster {{ ocp_install['ocp_cluster_vars']['cluster_id'] }}"
```

Affected code on every run reports ```changed```

```
TASK [ocp-install : Module: run_ocp_install_vault Task: create auth for the new cluster] *****************************************************************************************************************************************************************************************************************
changed: [localhost]
```

Ansible version:
```
ansible [core 2.11.6]
  config file = /Users/maslak/.ansible.cfg
  configured module search path = ['/Users/maslak/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/maslak/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.10 (main, Jan 15 2022, 11:48:04) [Clang 13.0.0 (clang-1300.0.29.3)]
  jinja version = 3.0.2
  libyaml = True
```

**Comment by TerryHowe** [comment]
Something wrong here maybe https://github.com/TerryHowe/ansible-modules-hashivault/blob/main/ansible/modules/hashivault/hashivault_auth_method.py#L109

https://github.com/TerryHowe/ansible-modules-hashivault/blob/357ce417a82da667ba6bacdbae2fe04d1c6e5097/ansible/module_utils/hashivault.py#L371

Although it looks kind of straight forward. Normally this boils down to things being represented differently when vault returns them even though they are equal

**Comment by siwyroot** [comment]
I will try to get some more data thru debug mode.

**Comment by ayav09** [comment]
It looks like vault will set them to system default (2764800 or 768hrs in a vanilla vault) for `default_lease_ttl` and `max_lease_ttl` if the parameter is zero so the module is trying to change it since 0 != 2764800. I think you should either set them to the values you want or remove them if the vault system default is fine.

**Comment by siwyroot** [comment]
> It looks like vault will set them to system default (2764800 or 768hrs in a vanilla vault) for `default_lease_ttl` and `max_lease_ttl` if the parameter is zero so the module is trying to change it since 0 != 2764800. I think you should either set them to the values you want or remove them if the vault system default is fine.

Hello, module behaves as expected with other values. When I login to UI I can see 0 values for both `max_lease_ttl` and `default_lease_ttl` but modules still reportes changed.

**Comment by Roxyrob** [comment]
Probably what @siwyroot tell about arguments set as default or not used can help. Not sure if this is the case but I noted that also using `|default(..)`  with the exact same defaults declared on API make changed on every run, e.g.:
<pre>
- hashivault_auth_method:
    token: "..."
    url: "..."
    method_type: "..."
    mount_point: "..."
    description: "..."
    state: "..."
    config:
      default_lease_ttl: "..."
      max_lease_ttl: "..."
      force_no_cache: "{{ item_auth.value.force_no_cache <b>| default(false)</b> }}"
      token_type: "{{ item_auth.value.token_type <b>| default('')</b> }}"
      listing_visibility: "{{ item_auth.value.listing_visibility <b>| default('')</b> }}"
  loop: "{{ hv_auth_cfg|dict2items }}"
  loop_control:
    loop_var: item_auth
</pre>

Probably variables defined also if not altered will change anyway underlying values returning changed state. This link tell us that "By default Ansible requires values for all variables in a templated expression"

* **[Making variables optional](https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#making-variables-optional)**.

In above code inside `config:`, arguments: `force_no_cache`, `token_type` and `listing_visibility` also if set to API default values, will make the module not idempotent. I changed default to omit to `omitting action option` and all worked fine:

<pre>
- hashivault_auth_method:
- hashivault_auth_method:
    token: "..."
    url: "..."
    method_type: "..."
    mount_point: "..."
    description: "..."
    state: "..."
    config:
      default_lease_ttl: "...}}"
      max_lease_ttl: "..."
      force_no_cache: "{{ item_auth.value.force_no_cache <b>| default(omit)</b> }}"
      token_type: "{{ item_auth.value.token_type <b>| default(omit)</b> }}"
      listing_visibility: "{{ item_auth.value.listing_visibility <b>| default(omit)</b> }}"
  loop: "{{ hv_auth_cfg|dict2items }}"
  loop_control:
    loop_var: item_auth
  no_log: "{{ no_log_flag }}"
</pre>

All optional arguments should be specified with `|default(omit)`. Hope this can help for your case too !

**Comment by siwyroot** [comment]
Hello, @Roxyrob thanks for W/A unfortunately it does not work for me (task is changed every time I run this), here is code that I'm using:

```
    - name: "Module: {{ module_name }} Task: create auth for the new cluster"
      hashivault_auth_method:
        url: "{{ ocp_install_vault_url }}"
        token: "{{ vault_login_raw.data.auth.client_token }}"
        mount_point: "ocp-install-{{ ocp_install['ocp_cluster_vars']['cluster_id'] }}"
        method_type: kubernetes
        description: "Authentication for flux automation for cluster {{ ocp_install['ocp_cluster_vars']['cluster_id'] }}"
        config:
          default_lease_ttl: 0
          max_lease_ttl: 0
          force_no_cache: "{{ ocp_install_vault_force_no_cache | default(omit) }}"
          token_type: "{{ ocp_install_vault_token_type | default(omit) }}"
          listing_visibility: "{{ ocp_install_vault_listing_visibility | default(omit) }}"
```
