### ISSUE TITLE
auth_method missing return value

### ISSUE THREAD

**Issue by ceesios** [TerryHowe/ansible-modules-hashivault#435]
The auth method has properties that cannot be defined such as the accessor.
It would be useful if the module would return the current config with all these properties so they can be used in other modules.
One such example woult be when creating a policy that references the accessor.

you would register the output like so:
```
- hashivault_auth_method:
    method_type: userpass
  register: auth_method_out
```

and if the return value would be called result use it as:
```
- name: debug auth_methods
  debug:
    msg: "{{ auth_method_out.result }}"
```

which will return something like:
```
  msg:
    accessor: auth_jwt_oatusd1j
    config:
      default_lease_ttl: 60
      force_no_cache: false
      max_lease_ttl: 60
      token_type: default-service
    description: jwt
    external_entropy_access: false
    local: false
    options: {}
    seal_wrap: false
    type: jwt
    uuid: oatusd1j-67a1-e99d-077a-d9f2baa0b5bb
```

In this case the accessor can be referenced by auth_method_out.result.accessor.

This can be done by registering all client actions as the `result` variable, not just the read. And returning the data from the current mountpoint as result.
If you like this idea i will make a pr.
