### ISSUE TITLE
Confused on correct approach to use this plugin

### ISSUE THREAD

**Issue by snoby** [TerryHowe/ansible-modules-hashivault#47]
Hi, 
Thank you for writing this wonderful plugin.  Using a simple playbook I can read values out of my vault instance no problem.  My playbook looks like this:
```
#
# This playbook is making the assumption that VAULT_ADDR is exported in the environment.
#
- hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    #    - debug: msg="The  jhaals vault plugin username secret is:{{ lookup('vault', 'secret/internal/CI/test', 'username') }}"

  - name: "Retrieve secrets from vault using the hashi_vault plugin"
    hashivault_read:
      secret: '/secret/internal/CI/test'
      key: 'username'
    register: 'vault_read_result'

  - debug:
      msg: "username={{ vault_read_result.value }}"
```

So in another playbook, the one that I want to retreive the actual vault key value, delegating to localhost, I get an error and I believe that it means that I've messed up somewhere because the module doesn't know the url to get to the vault nor does it know that I'm logged into my vault instance.
Here is the snippet of my playbook that uses the hashivault module:
```


- name: "Get the enterprise drone license from hashicorp vault"
  delegate_to: localhost
  hashivault_read:
    secret: 'secret/internal/CI/ccs_foo_com/jenkins-drone/drone-license'
    key: 'DRONE_LICENSE'
  register: 'vault_read_result'
  tags:
    - drone-server
    - drone-read

- name: "Setting fact DRONE_LICENSE"
  delegate_to: localhost
  set_fact:
    DRONE_LICENSE: "{{vault_read_result.value}}"
  when: "{{ vault_read_result.rc }} == 0"
  tags:
    - drone-server
    - drone-read

- assert: { that: "{{vault_read_result.rc}} == 0" }

```
Obviously I want to have my localhost machine get access to vault and then set the key value to a fact to be inserted into a template later in the playbook.  The error I'm getting is below:

```
fatal: [ci-master.ops.tropo.com -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "authtype": "token",
            "ca_cert": "",
            "ca_path": "",
            "client_cert": "",
            "client_key": "",
            "key": "DRONE_LICENSE",
            "password": "",
            "register": null,
            "role_id": "",
            "secret": "secret/internal/CI/ccs_foo_com/jenkins-drone/drone-license",
            "secret_id": "",
            "token": "",
            "url": "",
            "username": "",
            "verify": true
        }
    },
    "msg": "Exception: Invalid URL '/v1/secret/secret/internal/CI/ccs_foo_com/jenkins-drone/drone-license': No schema supplied. Perhaps you meant http:///v1/secret/secret/internal/CI/ccs_foo_com/jenkins-drone/drone-license?",
    "rc": 1
}
```
I've seen some mention of your action plugins, however I'm surprised that this work flow doesn't work.  Am I using this method wrong?  Should I run all my queries for secrets from localhost, set the facts then proceed to do the rest of the playbook and not do any type of delegation?
thanks,
Matt
