### ISSUE TITLE
enabling the kubernetes backend in 0.8.3

### ISSUE THREAD

**Issue by snoby** [TerryHowe/ansible-modules-hashivault#52]
I'm a bit confused as to how to use the hashivault_write command to configure this backend.
Here are the instructions on how to setup the backend: https://github.com/aws-samples/aws-workshop-for-kubernetes/tree/master/04-path-security-and-networking/401-configmaps-and-secrets#configure-kubernetes-auth-backend

Specifically need to configure it by writing  a token, the certificate authority and the server api to this backend.
```sh
 vault write auth/kubernetes/config \
  token_reviewer_jwt=$REVIEWER_TOKEN  \
  kubernetes_host=<api-server> \
  kubernetes_ca_cert=@~/.kube/kops.crt
```

thoughts?

**Comment by TerryHowe** [comment]
In theory, you should be able to write that with hashivault_write, but I haven't tested that.

**Comment by snoby** [comment]
indeed I agree with you, would I still use the key value as 'secret ' though?  
```

    - hashivault_write:
        secret: '/stories/stuart'
        data:
            last: 'little'
```

**Comment by TerryHowe** [comment]
I would guess `/auth/kubernetes/config`

**Comment by snoby** [comment]
Ok so I think I was able to make it work using this:
```
- name: "Configure the kubernetes backend in vault"
  hashivault_write:
    secret: 'auth/kubernetes/config'
    data:
      token_reviewer_jwt: "{{ JWT_REVIEWER_TOKEN }}"
      kubernetes_host: "proxy.api.{{ cluster_name }}"
      kubernetes_ca_cert: "{{ CA_PEM }}"
  register: CONFIG_WRITE_RESULT

```

This might be useful for the next guy that might need this...
