### ISSUE TITLE
hashivault_write with update tries to write empty string to unset values

### ISSUE THREAD

**Issue by perj** [TerryHowe/ansible-modules-hashivault#65]
Maybe this is not a problem in most cases, but for some secrets it matters.
E.g. here:

```
- hashivault_write:
    update: true
    secret: "/auth/aws/role/myrole"
    data:
      auth_type: ec2
      policies:
      - mypolicy
      disallow_reauthentication: true
      bound_iam_instance_profile_arn: "arn:aws:iam::1234:instance-profile/myinstanceprofile"
```

This works if the secret is new but if it already exists and I've changed the `bound_iam_instance_profile_arn` value then it fails with
```
"Exception: failed updating the unique ID of ARN \"\": &errors.errorString{s:\"unrecognized arn: contains 1 colon-separated parts, expected 6\"}"
```

My understanding is that this is because it tries to write empty string to the other arn-field (`bound_iam_principal_arn`)
