### ISSUE TITLE
Environment variable confusion

### ISSUE THREAD

**Issue by Flybro** [TerryHowe/ansible-modules-hashivault#78]
Hi, Sorry if my question is kind of immature but I really stumbled accross the following error:

```yaml
fatal: [etc01]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "authtype": "token", 
            "ca_cert": "", 
            "ca_path": "", 
            "client_cert": "", 
            "client_key": "", 
            "data": {
                "certificates": "abc"
            }, 
            "password": "", 
            "role_id": "", 
            "secret": "kafka", 
            "secret_id": "", 
            "token": "e75b7556-762d-ed89-1dca-9c3923187257", 
            "update": false, 
            "url": "", 
            "username": "", 
            "verify": true
        }
    }, 
    "msg": "Exception: Invalid URL '/v1/secret/kafka': No schema supplied. Perhaps you meant http:///v1/secret/kafka?", 
    "rc": 1
}
```
I'm trying to run playbook on remote machine. All neccessary variable are set but still no go. Looks like module is not reading env. The token is readed form .vault-token on remote machine instead from env.
This is how I run it:

```yaml
ansible-playbook -i poc.inv -e VAULT_ADDR=https://bunsen:8200 -e VAULT_TOKEN=e75b7556-762d-ed89-1dca-9c3923187258 poc.yml
```
poc.yml
```yaml
---
- hosts: poc
  roles:
    - vault
```

main.yml:
```yaml
---
- name: Write secrets
  hashivault_write:
    secret: 'kafka'
    data:
      certificates: 'abc'
  register: 'vault_write'
```

Any thoughts about how it should be done, please?
Cheers,
BB
