### ISSUE TITLE
policy creation is not idempotent

### ISSUE THREAD

**Issue by drewmullen** [TerryHowe/ansible-modules-hashivault#81]
My playbook is simple: 
1. cat the contents of a *.hcl policy file and register to {{ file_contents }}
2. create the policy using "hashivault_policy_set"
   - name is derived from the policy file name (same name but minus the .hcl)
   - content is derived from the {{ file_contents.stdout }}

# error

## successful run
$ ansible-playbook tasks/set_policy/vault_set_policy.yml -i tasks/set_policy/inv -e "policy_file=./policies/app_awx.hcl"

PLAY [all] **********************************

TASK [cat file] ****************************
changed: [localhost -> localhost]

TASK [set policy from file contents] **
changed: [localhost -> localhost]

PLAY RECAP ****************************************
localhost                  : ok=2    changed=2    unreachable=0    failed=0   

## rerunning yields failure
$ ansible-playbook tasks/set_policy/vault_set_policy.yml -i tasks/set_policy/inv -e "policy_file=./policies/app_awx.hcl"

PLAY [all] *****************************************

TASK [cat file] ********************************************
changed: [localhost -> localhost]

TASK [set policy from file contents] ****************************************************
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "msg": "Exception: u'rules'", "rc": 1}

PLAY RECAP *********************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=1

# playbook

```
---

- hosts: all
  strategy: linear
  gather_facts: false
  tasks:

  - name: cat file
    local_action: shell cat "{{ policy_file }}"
    register: file_contents

  - name: set policy from file contents
    hashivault_policy_set:
      name: "{{ (policy_file.split('.')[0]) | basename | string }}"
      rules: "{{ file_contents.stdout }}"
    delegate_to: localhost
```

# verbose error
```
fatal: [localhost -> localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "authtype": "token", 
            "ca_cert": "", 
            "ca_path": "", 
            "client_cert": "", 
            "client_key": "", 
            "name": "app_awx", 
            "password": "", 
            "role_id": "", 
            "rules": "path \"secret/*\" { capabilities = [\"list\"] }\n\npath \"secret/data/lob/*\" { capabilities = [\"list\", \"read\", \"update\", \"create\", \"delete\"] }\n\npath \"secret/metadata/lob/*\" { capabilities = [\"list\", \"read\", \"delete\"] }", 
            "secret_id": "", 
            "token": "<my token>", 
            "url": "https://vault.example.com:8200", 
            "username": "", 
            "verify": false
        }
    }, 
    "msg": "Exception: u'rules'", 
    "rc": 1
}
```
