### ISSUE TITLE
How do I enable github auth backend and assign policies to teams/users?

### ISSUE THREAD

**Issue by riuvshin** [TerryHowe/ansible-modules-hashivault#84]
Hello, first of all I want to say thanks for the great module :)

But I need some help here... I stuck on getting github auth configured.

I basically need few things:
1) `vault write auth/github/config organization=my-awesome-org`
2) `vault write auth/github/map/teams/default value=very-cool-policy-for-default-team-in-my-awesome-org`
3) `vault write auth/github/map/users/developer value=very-cool-policy-for-user-developer-in-my-awesome-org`

it basically should be covered by `hashivault_write` / `hashivault_read` as there is nothing special, but I do not see this covered in the docs so wonder if this is supported...

**Comment by riuvshin** [comment]
so it works as I thought simply by writing a secret
```
---
- name: "[auth-backend] Enable github auth"
  hashivault_auth_enable:
    name: "github"

- name: "[auth-backend] Configure github auth"
  hashivault_write:
    secret: '/auth/github/config'
    data:
      organization: 'my-awesome-org'
      base_url: ''
      max_ttl: 0
      ttl: 0

- name: "apply policy for gh team: default"
  hashivault_write:
    secret: '/auth/github/map/teams/default'
    data:
      value: 'very-cool-policy-for-default-team-in-my-awesome-org'

- name: "apply policy for gh user: developer"
  hashivault_write:
    secret: '/auth/github/map/users/developer'
    data:
      value: 'very-cool-policy-for-user-developer-in-my-awesome-org,default'
```
