### ISSUE TITLE
Key in write data does not expand

### ISSUE THREAD

**Issue by michalmedvecky** [TerryHowe/ansible-modules-hashivault#9]
Sample:

```yaml
- hosts: localhost
  vars: 
    - key: "key123"
    - value: "value123"
  tasks:
    - hashivault_write:
      secret: "/cesta/k/jebnutemu/secretu"
        data:
          "{{ key }}": "{{ value }}"
```

```
$ vault read /cesta/k/jebnutemu/secretu
Key                    Value
---                    -----
refresh_interval       168h0m0s
{{ key }}              value123
```

**Comment by TerryHowe** [comment]
I've seen this before and it is really an ansible issue:

https://github.com/ansible/ansible/issues/17324

**Comment by michalmedvecky** [comment]
Okay for desperates like me, one can do

```yaml
- hosts: localhost
  vars: 
    - key: "key123"
    - value: "value123"
  tasks:
    - hashivault_write:
      secret: "/cesta/k/jebnutemu/secretu"
        data:
          "{'{{ key }}': '{{ value }}'}"
```

**Comment by TerryHowe** [comment]
In theory this should work too:
```
- hosts: localhost
  vars: 
    - key: &key "key123"
    - value: "value123"
  tasks:
    - hashivault_write:
      secret: "/cesta/k/jebnutemu/secretu"
        data:
          *key: "{{ value }}"
```

**Comment by michalmedvecky** [comment]
Hard to use with `with_items` though

**Comment by TerryHowe** [comment]
Reopening this to document this common issue

**Comment by absynth76** [comment]
For info, I used this way:
```
- hosts: localhost
  vars: 
    - key: "key123"
    - value: "value123"
  tasks:
  - hashivault_write:
      secret: my-secret
      data: "{{ my_new_data }}"
      version: 2
    vars:
      my_new_data: "{{ {key:value} }}"
```
you can even loop with that I guess
